"""init profiles

Revision ID: 05c9449a6d9d
Revises: 0002_init_profiles
Create Date: 2026-04-16 23:37:04.084790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '05c9449a6d9d'
down_revision: Union[str, None] = '0002_init_profiles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'surf_level',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('profiles_id_fkey'), 'profiles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('profiles_id_fkey'), 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.alter_column('profiles', 'surf_level',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
